### ISSUE TITLE
LDAP SSL Certification on Active Directory Server 

### ISSUE THREAD

**Issue by It-All-JJEI** [It-All-JJEI/Rental_Live#1]
When trying to bind to LDAP the error LDAP - Strong(er) authentication required. but only intermittently. 
The reason may be that there is no SSL rule enabled on the AD server
![screenshot_4](https://user-images.githubusercontent.com/40477784/43208913-79123b52-8ff9-11e8-959a-47dbb1e5fb8c.png)

**Comment by rodgersj097** [comment]
Created LDAP over SSL on 40-targit01 to strengthen ldap_bind secure key. Solved intermittent login failure
