### ISSUE TITLE
Correct Date values 

### ISSUE THREAD

**Issue by It-All-JJEI** [It-All-JJEI/Rental_Live#5]
When a date field is empty is MSSQL it automatically sets the value as 01-01-1900, use strotime to fix

**Comment by rodgersj097** [comment]
Fixed date issue with MSSQL dealing with empty date values as 1900-01-0. 
	   ` 
	   
	    if($unit['eta']='1900-01-01') {
			$unit['eta'] = null; }
		else{
			$unit['eta']; }`
Used above code to fix
